name: Github actions pytest
on: ['push', 'pull_request']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - 'python-3.4'
        - 'python-3.5'
        - 'python-3.6'
        - 'python-3.7'
        - 'python-3.8'
        - 'python-3.9'
        - 'python-3.10'
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: install
      run: |
        python -m pip install pytest-cov
    - name: run-tests
      run: |
        python -m pytest --cov-report= --cov=pyluach tests/
  release:
    needs: build
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}